import type { NextPage } from 'next';
import Router, { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import Header from '../components/Header';
import useUserObject from '../hooks/useUserObject';

const Home: NextPage = () => {
  const userHookObject = useUserObject();
  const { userObj } = userHookObject;

  const getFrontPagePosts = () => {
    fetch('http://localhost:4000/posts', {
      method: 'GET',
      headers: {
        frontpage: 'true',
      },
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
      });
  };

  useEffect(() => {
    getFrontPagePosts();
  }, []);
  return (
    <>
      <Head>
        <title>Bloggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header userObj={userObj} />
      <div className={styles.container}>
        <main className={styles.main}></main>

        <footer className={styles.footer}></footer>
      </div>
    </>
  );
};

export default Home;
