import type { NextPage } from 'next';
import Router, { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import dynamic from 'next/dynamic';

const Header = dynamic(() => import('../components/Header'), { ssr: false });
import FeaturedPost from '../components/frontPage/FeaturedPost';
import FrontPageMain from '../components/frontPage/FrontPageMain';
import useUserObject from '../hooks/useUserObject';
import blogPostObjInterface from '../shared/interfaces/blogPostObj.interface';

export async function getStaticProps() {
  const data = await fetch('http://localhost:4000/posts/published', {
    method: 'GET',
    
  });

  const posts = await data.json();
  console.log(posts);
  return {
    props: {
      posts,
    },
  };
}

const Home: NextPage<{
  posts: blogPostObjInterface[];
}> = ({ posts }) => {
  const userHookObject = useUserObject();
  const { userObj } = userHookObject;
  console.log(posts);
  return (
    <>
      <Head>
        <title>Bloggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header userObj={userObj} />
      <div className="h-full relative">
        <main className="min-h-screen h-screen flex flex-col justify-start">
          <FeaturedPost posts={posts} />
          <FrontPageMain posts={posts} />
        </main>
      </div>
    </>
  );
};

export default Home;
