import type { NextPage } from 'next';
import Router, { useRouter } from 'next/router';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Register.module.scss';
import useUserObject from '../hooks/useUserObject';

const Register: NextPage = () => {
  const [errors, setErrors] = useState<
    [
      {
        value: String;
        msg: String;
        param: String;
        location: String;
      }
    ]
  >([{ msg: '', value: '', param: '', location: '' }]);

  const userHookObject = useUserObject();
  const { userObj } = userHookObject;

  const router = useRouter();

  const ISSERVER = typeof window === 'undefined';

  const handleSubmit = async (data: any) => {
    const { firstName, lastName, email, password, confirmPassword } = data;

    console.log(email.value, password.value);

    const response = await fetch('http://localhost:4000/users', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        firstName: firstName.value,
        lastName: lastName.value,
        email: email.value,
        password: password.value,
        confirmPassword: confirmPassword.value,
      }),
    });
    const json = await response.json();

    if (json.user) {
      router.push('/login');
    } else {
      setErrors(json.errors);
    }
  };
  useEffect(() => {
    if (userObj) {
      router.push('/');
    }
  }, [userObj]);
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/backgrounds/register_background.jpg"
          layout="fill"
          objectFit="cover"
          alt="background"
        />

        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSubmit(e.target);
          }}
          method="POST"
          className={styles.form}
          data-testid="login-form"
        >
          <label htmlFor="firstName" className={styles.label}>
            First Name
            <input type="text" id="firstName" className={styles.input} />
          </label>
          <label htmlFor="lastName" className={styles.label}>
            Last Name
            <input type="text" id="lastName" className={styles.input} />
          </label>
          <label htmlFor="email" className={styles.label}>
            Email
            <input type="email" id="email" className={styles.input} required />
          </label>

          <label htmlFor="password" className={styles.label}>
            Password
            <input
              type="password"
              id="password"
              className={styles.input}
              required
            />
          </label>
          <label htmlFor="confirmPassword" className={styles.label}>
            Confirm Password
            <input
              type="password"
              id="confirmPassword"
              className={styles.input}
              required
            />
          </label>

          {errors[0].msg !== '' ? (
            <ul>
              {errors.map((error, index) => (
                <li key={index} className="error">
                  {' '}
                  {error.msg}
                </li>
              ))}
            </ul>
          ) : null}
          <button type="submit">Create Account</button>
          <p>
            Already have an account?{' '}
            <Link href="/login">
              <a>Login</a>
            </Link>
          </p>
          <p>
            Return to{' '}
            <Link href="/">
              <a>Home</a>
            </Link>
          </p>
        </form>
      </main>

      <footer></footer>
    </>
  );
};

export default Register;
